package com.anotherproject.marksproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Marks implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int marks;

	public Marks() {
	}

	public int getMarks() {
		return this.marks;
	}

	public void setMarks(int marks) {
		this.marks = marks;
	}

	public String toString() {
		return String.valueOf(marks);
	}

	public Marks(int marks) {
		this.marks = marks;
	}

}