package com.anotherproject.marksproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StudentInformation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String studentName;
	private int studentId;

	public StudentInformation() {
	}

	public java.lang.String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(java.lang.String studentName) {
		this.studentName = studentName;
	}

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public StudentInformation(java.lang.String studentName, int studentId) {
		this.studentName = studentName;
		this.studentId = studentId;
	}

}